% Plots 2 figures, one with all the individual plots of the not-shifted birds,
% and one with all the shifted-birds from the csv file generated by genfeatures.m
% E.g. plot_csv('data_1_avg.csv')
function plot_csv(filename)
	dataset = csvread(filename);
	shifted = dataset(dataset(:, 7) == 1, :);
	not_shifted = dataset(dataset(:, 7) == 0, :)

	n = size(dataset, 2) - 7;

	% add time
	X = [];
	t = datenum([2000, 1, 1, 0, 0, 0]);
	interval = (24 * 60 * 60) / n

	for j=1:n
		X(j) = t;
		t = addtodate(t, interval, 'second');
	end

	size(not_shifted)

	plot(X, not_shifted(:, 8:end));
	title('Not shifted')
	% legend(strtrim(cellstr(num2str(not_shifted(:,1:4)))'));
	datetick('x', 'HH');
	figure;
	plot(X, shifted(:, 8:end));
	title('Shifted')
	% legend(strtrim(cellstr(num2str(shifted(:,1:4)))'));
	datetick('x', 'HH');
end
