% Plots the averages of not-shifted and shifted birds from the csv file
% generated by genfeatures.m. E.g.: plot_dataset('data_1_avg.csv')
function plot_csv_avg(filename)
	dataset = csvread(filename);
	shifted = dataset(dataset(:, 7) == 1, :);
	not_shifted = dataset(dataset(:, 7) == 0, :)

	n = size(dataset, 2) - 7;

	% add time
	X = [];
	t = datenum([2000, 1, 1, 0, 0, 0]);
	interval = (24 * 60 * 60) / n

	for j=1:n
		X(j) = t;
		t = addtodate(t, interval, 'second');
	end

	size(not_shifted)

	hold on
	plot(X, nanmean(not_shifted(:, 8:end)));
	plot(X, nanmean(shifted(:, 8:end)));
	hold off
	% legend(strtrim(cellstr(num2str(shifted(:,1:4)))'));
	legend('not-shifted avg', 'shifted avg');
	datetick('x', 'HH');
end
