% Plots the csv generated by genfeatures.m
function plot_dataset(filename)
	dataset = csvread(filename);

	shifted = dataset(dataset(:, 7) == 1, :);
	not_shifted = dataset(dataset(:, 7) == 0, :);

	n = size(not_shifted, 1);

	for i = 1:n
		subplot(n, 1, i);
		plot(not_shifted(i, 8:end));
	end
end