% Plots the csv generated by genfeatures.m
function plot_dataset(filename)
	dataset = csvread(filename);
	shifted = dataset(dataset(:, 7) == 1, :);
	not_shifted = dataset(dataset(:, 7) == 0, :);

	n = size(dataset, 2) - 7;

	% add time
	X = [];
	t = datenum([2000, 1, 1, 0, 0, 0]);
	interval = (24 * 60 * 60) / n

	for j=1:n
	    X(j) = t;
	    t = addtodate(t, interval, 'second');
	end

	plot(X, not_shifted(:, 8:end));
	datetick('x', 'HH');
end