% Generates plot to show the variances for shifted and each day after shifted
% features from a csv file generated by genfeatures.m
%
% e.g. plot_var('data_6_avg.csv', zeros(1, 4))	% For not shifting of the plot
%
% The shift vector can be used to shift the shifted birds on a per-day basis.
% E.g., shift = [10, 20, 30, 40] shifts the birds with a 6min interval
% 1 hour to the right for the birds that have been shifted 1 day,
% 2 hours to the right for the birds that have been shifted 2 days, etc.
% The shift vector is the number of INTERVALS that should be shifted.
%
function plot_var(filename, shift)
	% Get the averages of shifted, and day 1, 2, 3, 4 shifted
	dataset = dlmread(filename, ',', 0, 0);
	n = size(dataset, 2) - 7;
	num_intervals = size(dataset, 2) - 7;
	interval_size = 24*3600/num_intervals

	% Separate shifted and non-shifted dataset
	not_shifted = dataset(dataset(:, 7) == 0, :);
	shifted = dataset(dataset(:, 7) == 1, :);

	% Create a matrix for the first day after the shifting takes place..
	shifted_1 = dataset([5, 12, 16, 23, 28], :);

	% And the second...
	shifted_2 = dataset([6, 13, 17, 24, 29], :);

	% Third...
	shifted_3 = dataset([7, 18, 25, 30], :);

	% And fourth day.
	shifted_4 = dataset([8, 19], :);

	% Extra day?
	shifted_5 = dataset([9], :);

	% And some data that has been unshifted...
	shifted_back = dataset([20], :);

	% add time
	X = [];
	t = datenum([2000, 1, 1, 0, 0, 0]);
	interval = (24 * 60 * 60) / n

	for j=1:n
		X(j) = t;
		t = addtodate(t, interval, 'second');
	end

	% Plot all the subplots....
	figure;
	hold on;
	numplots = 7;
	ymax = 0.01

	subplot(numplots, 1, 1)
	plot(X, nanvar(not_shifted(:, 8:end)));
	datetick('x', 'HH');
	ylim([0, ymax])
	legend('not shifted (15 birds)');

	subplot(numplots, 1, 2)
	plot(X, circshift(nanvar(shifted_1(:, 8:end)), [0, shift(1)]));
	datetick('x', 'HH');
	ylim([0, ymax])
	legend('day 1 (5 birds)');

	subplot(numplots, 1, 3)
	plot(X, circshift(nanvar(shifted_2(:, 8:end)), [0, shift(2)]));
	datetick('x', 'HH');
	ylim([0, ymax])
	legend('day 2 (5 birds)');

	subplot(numplots, 1, 4)
	plot(X, circshift(nanvar(shifted_3(:, 8:end)), [0, shift(3)]));
	datetick('x', 'HH');
	ylim([0, ymax])
	legend('day 3 (4 birds)');

	subplot(numplots, 1, 5)
	plot(X, circshift(nanvar(shifted_4(:, 8:end)), [0, shift(4)]))
	datetick('x', 'HH');
	ylim([0, ymax])
	legend('day 4 (2 birds)');

	subplot(numplots, 1, 6)
	plot(X, zeros(1, num_intervals))
	datetick('x', 'HH');
	ylim([0, ymax])
	legend('day 5 (1 bird)');

	subplot(numplots, 1, 7)
	plot(X, zeros(1, num_intervals))
	datetick('x', 'HH');
	ylim([0, ymax])
	legend('day 5, shifted back (1 bird)');

	hold off;
