% Generates plot to show the averages for shifted and each day after shifted
% features from a csv file generated by genfeatures.m
%
% e.g. test_shift('data_6_avg.csv', zeros(1, 4))
%
% The shift vector can be used to shift the shifted birds on a per-day basis.
% E.g., shift = [-10, -20, -30, -40] shifts the birds with a 6min interval
% 1 hour to the left for the birds that have been shifted 1 day,
% 2 hours to the left for the birds that have been shifted 2 days, etc.
function test_shift(filename, shift)
	% Plot the averages of shifted, and day 1, 2, 3, 4 shifted
	dataset = dlmread(filename, ',', 0, 0);
	n = size(dataset, 2) - 7;
	num_intervals = size(dataset, 2) - 7;
	interval_size = 24*3600/num_intervals

	% Separate shifted and non-shifted dataset
	not_shifted = dataset(dataset(:, 7) == 0, :);
	shifted = dataset(dataset(:, 7) == 1, :);

	% Create a matrix for the first day after the shifting takes place..
	shifted_1 = dataset([5, 12, 16, 23, 28], :);

	% And the second...
	shifted_2 = dataset([6, 13, 17, 24, 29], :);

	% Third...
	shifted_3 = dataset([7, 18, 25, 30], :);

	% And fourth day.
	shifted_4 = dataset([8, 19], :);

	% Extra day?
	shifted_5 = dataset([9], :);

	% And some data that has been unshifted... herp?
	shifted_back = dataset([20], :);

	% add time
	X = [];
	t = datenum([2000, 1, 1, 0, 0, 0]);
	interval = (24 * 60 * 60) / n

	for j=1:n
	    X(j) = t;
	    t = addtodate(t, interval, 'second');
    end

    % Plot aids and ebola with bird flu
    figure;
    hold on;
    numplots = 5;
    ymax = 0.02

    subplot(numplots, 1, 1)
	plot(X, nanmean(not_shifted(:, 8:end)));
	datetick('x', 'HH');
	ylim([0, ymax])
    legend('not shifted');

    subplot(numplots, 1, 2)
	plot(X, circshift(nanmean(shifted_1(:, 8:end)), [0, shift(1)]));
	datetick('x', 'HH');
	ylim([0, ymax])
    legend('day 1');

    subplot(numplots, 1, 3)
	plot(X, circshift(nanmean(shifted_2(:, 8:end)), [0, shift(2)]));
	datetick('x', 'HH');
	ylim([0, ymax])
    legend('day 2');

    subplot(numplots, 1, 4)
	plot(X, circshift(nanmean(shifted_3(:, 8:end)), [0, shift(3)]));
	datetick('x', 'HH');
	ylim([0, ymax])
    legend('day 3');

    subplot(numplots, 1, 5)
	plot(X, circshift(nanmean(shifted_4(:, 8:end)), [0, shift(4)]))
	datetick('x', 'HH');
	ylim([0, ymax])
    legend('day 4');

	% plot(X, nanmean(shifted_5(:, 8:end)));
	% plot(X, nanmean(shifted_back(:, 8:end)));
    % legend(strtrim(cellstr(num2str(not_shifted(:,1:4)))'));
    % legend('not shifted', 'day 1', 'day 2', 'day 3', 'day 4', 'day 5', 'shifted back');
    hold off;
